# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set the working directory to /app
WORKDIR /app

COPY server/database.sql /docker-entrypoint-initdb.d/
COPY server/fakedata.sql /docker-entrypoint-initdb.d/
COPY server/queries.sql /docker-entrypoint-initdb.d/
COPY server/users.sql /docker-entrypoint-initdb.d/
COPY server/userskills.sql /docker-entrypoint-initdb.d/