FROM node:16.13
# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY server/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server code to the container
COPY server/ .

# Expose port 5000
EXPOSE 5000

# Start the app
CMD ["npm", "start"]