insert into userskill (userid, skill) values
    (27, 'Java'), (32, 'Python'), (30, 'C++'), (10, 'JavaScript'), (48, 'C#'), (37, 'Ruby'), (20, 'Swift'), (48, 'Go'), (6, 'Kotlin'), (33, 'PHP'), (7, 'TypeScript'), (15, 'Scala'),
    (37, 'Assembly'), (3, 'R'), (27, 'HTML'), (11, 'CSS'), (33, 'JavaScript frameworks'), (4, 'Node.js'), (15, 'RESTful API design and development'), (48, 'Database integration'),
    (40, 'Web security'), (33, 'Responsive design and cross-browser compatibility'), (4, 'Server-side languages'), (30, 'Deployment and hosting'), (16, 'CMS'), 
    (2, 'Debugging and problem-solving'), (26, 'SQL'), (47, 'NoSQL databases'), (7, 'Data modelling and normalization'), (4, 'Database administration'), (35, 'Data warehousing'), 
    (48, 'Indexing and query optimization'), (3, 'Backup and recovery'), (32, 'Security and access control'), (48, 'Data migration'), (36, 'ETL processes'), (2, 'Agile'),
    (12, 'Waterfall'), (40, 'Lean'), (35, 'DevOps'), (2, 'Test-Driven Development (TDD)'), (5, 'Behaviour-Driven Development (BDD)'), (28, 'Feature-Driven Development (FDD)'), 
    (42, 'Spiral'), (20, 'Rapid Application Development (RAD)'), (26, 'Extreme Programming (XP)'), (5, 'Hybrid'), (10, 'Git'), (3, 'SVN (Apache subversion)'), (7, 'Mercurial'), 
    (29, 'Source control management concepts'), (1, 'Command line interface usage'), (2, 'Distributed version control systems'), (45, 'Collaborative development practices'), 
    (11, 'Code reviews and issue tracking'), (6, 'Conflict resolution'), (39, 'Cloud platforms'), (2, 'Virtualization technologies'), (45, 'Infrastructure as Code (IAC) tools'), 
    (8, 'Container orchestration'), (41, 'Serverless computing'), (46, 'Networking and security'), (26, 'Database and storage services'), (12, 'Monitoring and logging'), 
    (32, 'Automation and configuration management'), (43, 'Cost optimization and management'), (41, 'Windows administration'), (24, 'Linux administration'), (17, 'MacOS administration'), 
    (6, 'Command line usage'), (31, 'Network configuration and troubleshooting'), (11, 'User and group management'), (40, 'File system management and backup'), 
    (13, 'Security and acccess control'), (18, 'Process and resource management'), (42, 'Virtualization'), (23, 'Package management and software installation'), 
    (4, 'Scripting and automation'), (36, 'Networking protocols'), (24, 'Router and switch configuration'), (36, 'Firewall administration'), (36, 'VPN setup'), (20, 'Network security'), 
    (17, 'Web application security'), (3, 'Intrusion detection and prevention'), (23, 'Security information and event management'), (45, 'Disaster recovery'), 
    (27, 'Compliance and regulatory requirements'), (2, 'iOS development'), (45, 'Android development'), (38, 'Cross-platform development frameworks'), (27, 'Mobile UI and UX design'), 
    (35, 'RESTful API integration'), (30, 'Database design and integration'), (32, 'Mobile security'), (50, 'Push notifications'), (34, 'In-app purchases'), 
    (4, 'Compatibility and testing'), (33, 'Mathematical foundations'), (15, 'Deep learning frameworks'), (15, 'Natural language processing (NLP)'), (41, 'Computer vision'), 
    (1, 'Reinforcement learning'), (30, 'Model selection and evaluation'), (25, 'Data pre-processing and feature engineering'), (22, 'Cloud computing for AI and ML'), 
    (41, 'Experimentation and iteration in model development');
